Add base template
nearform/node-cephes pull request #10
Opened 2022-08-08 07:01 UTC by Thurfjell

Adhere to [Bench Template](https://github.com/nearform/bench-template) standard of configurations and practices.

2022-08-08 07:50 UTC, simoneb requested changes
See inline comments, plus, this is missing all the workflows that are in the template repo

2022-08-08 07:50 UTC, simoneb commented on article/lib/lazy-graphs.js
> +const d3 = require('../d3.js')
to limit the extent of changes, let's keep the semicolons in the prettier configuration

2022-08-08 07:50 UTC, simoneb commented on build/generate-readme-toc.js
> +/* eslint-disable no-useless-escape */
let's disable this rule in the config so it's easier to remember to go back to it in the future

2022-08-08 07:51 UTC, simoneb commented
Please link the issue in the PR description and avoid including links to the private repo

2022-08-09 13:21 UTC, RafaelGSS commented on .github/dependabot.yml
> +      interval: 'daily'
I recommend changing it to weekly. `daily` tends to be very annoying

2022-08-09 13:21 UTC, RafaelGSS commented on .github/workflows/ci.yml
> +      - run: |
```suggestion
      - name: Install dependencies
        run: |
```

2022-08-09 13:21 UTC, RafaelGSS commented on .github/workflows/ci.yml
> +          sudo apt install -y nodejs
```suggestion
```
You don't need to install `nodejs` once it will be installed by the `actions/setup-node`.

2022-08-09 13:21 UTC, RafaelGSS commented on .github/workflows/ci.yml
> +          git clone https://github.com/emscripten-core/emsdk.git
I'd move the `emsdk` installation to another _step_

2022-08-09 13:21 UTC, RafaelGSS commented on .nvmrc
> +16
Isn't 18 supported?

2022-08-09 13:21 UTC, RafaelGSS commented on Makefile
> +	@# clang-rename \
Would you mind explaining why those changes were required in the Makefile?

2022-08-09 14:35 UTC, Thurfjell commented on .github/dependabot.yml
> +      interval: 'daily'
Hehe sorry, this was straight from the base template.

2022-08-09 14:36 UTC, Thurfjell commented on .nvmrc
> +16
Straight from the base template again :(

2022-08-09 14:58 UTC, Thurfjell commented on Makefile
> +	@# clang-rename \
Sure, this draft commit is kind of 'in the middle of figuring it out'. for me.  Anyway I wanted it to compile and run tests, and I had issues to get clang installed easily and quickly, so I figured ill remove it for a poc if you will. According to docs and comments, this is seems like a rename to remove kind of deal, so I figure Id just remove the files instead of renaming. clang-rename wasn't entirely obvious. clang-tools? clang itself? (pretty big?).

2022-08-09 14:59 UTC, Thurfjell commented on .github/workflows/ci.yml
> +          git clone https://github.com/emscripten-core/emsdk.git
Sure, if continuing this, a proper refactor to put each part in it's place is warranted. I just wanted it to work first.

2022-08-09 16:21 UTC, RafaelGSS commented on Makefile
> +	@# clang-rename \
Oh, okay. So, it's not compiling currently?

2022-08-09 16:24 UTC, simoneb commented on Makefile
> +	@# clang-rename \
@RafaelGSS please check this repo out and try compiling. The reason why we're doing this is because @Thurfjell couldn't make it work locally, and I guess we assumed it would not work on GH actions either (which is what we're trying to do here). We would like to put ourselves in a position to be able to make new releases of this package, and a prerequisite for that is that we can compile it

2022-08-10 09:09 UTC, closed without merging